export const state = {
    mainImageFile: null,
    referenceImageFiles: [],
    maskDataUrl: null,
    isSending: false,
    lastGeneratedImageForEditing: null,
    isContextPreviewHidden: false,
    sessions: [],
    currentSessionId: null,
    pendingBaseImageShare: false,
    pendingReferenceImageShares: new Set(),
    lastGenerationContext: null,
    userAssets: [],
    workbenchItems: new Map(),
    draggedWorkbenchItem: null,
    currentActiveWorkbenchItemId: null,
    currentIntentLock: null,
    activeConnectors: [],
    collisionTargetId: null,
    injectionSourceId: null,
    selectionBox: null,
    isSelecting: false,
    selectionStart: { x: 0, y: 0 },
    selectedWorkbenchItems: new Set(),
    isCtrlPressed: false,
    isAltPressed: false,
    workbenchItemCount: 0,
    isCropping: false,
    croppingItemId: null,
    latentState: {
        isDrawing: false,
        ctx: null,
        lastX: 0,
        lastY: 0,
        debounceTimer: null,
        isGenerating: false,
        tool: 'pencil',
        history: [],
        backgroundColor: '#ffffff',
        seed: Math.floor(Math.random() * 1000000000)
    },
    isPanning: false,
    isSpacePressed: false,
    panStartX: 0,
    panStartY: 0,
    panOffsetX: 0,
    panOffsetY: 0,
    workbenchZoom: 0.2,
    selectedModel: 'gpt-image-2',
    thinkingLevel: 'LOW',
    maskEditor: {
        isDrawing: false,
        imageCanvas: null,
        drawingCanvas: null,
        ctx: null,
        scale: 1,
        activeFile: null,
        points: [],
        hasSelection: false,
        globalMoveListener: null,
        globalUpListener: null,
        toolMode: 'lasso',
        boxStart: null
    },
    fileToWorkbenchIdMap: new Map()
};
